name: curso-jupyter
dependencies:
- nodejs
- jupyterlab==3.0.14
- pandas==1.1.3
- numpy==1.19.2
- scipy==1.5.2
- fuzzywuzzy==0.18.0
- IPython==7.19.0
- sklearn
- matplotlib==3.3.2
- seaborn==0.11.0
- ipywidgets==7.5.1
- xlrd==1.2.0
- python-Levenshtein==0.12.2
- jupyterlab-widgets==1.0.0
- plotly==4.14.3
- cufflinks==0.17.3
- retrolab==0.2.2